Avoid compilation errors with libtirpc
libtirpc sets the structure to sockaddr_in6 which causes the following
compile errors:

> daemon.c: In function 'get_remote':
> daemon.c:113:43: error: 'struct sockaddr_in6' has no member named 'sin_addr'
> return (svc_getcaller(rqstp->rq_xprt))->sin_addr;
> ^
> daemon.c: In function 'get_port':
> daemon.c:121:43: error: 'struct sockaddr_in6' has no member named 'sin_port'
> return (svc_getcaller(rqstp->rq_xprt))->sin_port;

The answer is to cast it back from sockaddr_in6 to sockaddr_in as they
are suppose to be backward compatible.